# -*- coding: utf-8 -*-
"""Red_de_juguete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12S_ElIoF5yEdTWZt6Lzhr4z-x5uGdFBK

Probar variaciones de:

Variar cantidad de capas y neuronas profundas (las de salida y entrada son fijas).

Función de activacion h = F.relu(hidden(h))

variar cantidad de epochs

variar criterion (funcion de costo o perdida)

variar métrica (accuracy, etc)

cantidad de kfolds y cantidad de mini_batchs

variar el dataset.
"""



import torch
import torch.nn as nn #Módulos para las redes neuronales
import torch.optim as optim #Algoritmos de optimización
from torch.utils.data import DataLoader, Subset, TensorDataset #Manejo y carga de datasets
from sklearn.model_selection import KFold #Validación cruzada con los kfolds
import torch.nn.functional as F #Funciones útiles-> funciones de agregación. Él uso "relu" pero pueden ser otras
import numpy as np #Operaciones matemáticas, arrays
import matplotlib.pyplot as plt #Gráficos, visualizaciones
import os #Funciones del Sist Oper y de archivos
import time #Para medir los tiempos y pausas
import torchvision #Datasets y utilidades para mostrar la visión de las neuronas artificiales
import torchvision.transforms as transforms #Transformaciones para imágenes--- le mandas la imagen y la analiza CHEQUEAR!!!!

class MLP(torch.nn.Module):
    """
    Multilayer perceptron (MLP) // Perceptríon Multicapa .

    Esta clase define una red neuronal feedforward con múltiples capas ocultas
    lineales, funciones de activación tangente hiperbólica en  las capas ocultas
    y una salida lineal.

    Args:
        sizes (lista): Lista de enteros que especifica el número de neuronas en
        cada capa. El primer elemento debe coincidir con la dimensión de entrada
        y el último con la dimensión de salida.

    Atributos:
        capas (torch.nn.ModuleList): Lista que contiene las capas lineales del MLP.

    Métodos:
        forward(x): Realiza una pasada hacia adelante a través de la red MLP.

    Ejemplo:
        tamaños = [entrada_dim, oculta1_dim, oculta2_dim, salida_dim]
        mlp = MLP(tamaños)
        tensor_entrada = torch.tensor([...])
        salida = mlp(tensor_entrada)
    """

    #Constructor
    def __init__(self,sizes): #Sizes es una lista con el tamaño de cada capa
        super().__init__() #Inicializa clase padre--> nn.Modula. Básicamente hace que pytorch pueda reconocer a esta clase como una red neuronal
        self.layers = torch.nn.ModuleList() #esto es como una lista de capas que ya se pueden aplicar sobre tensores. ModuleList registra automáticamente las capas de entrenamiento
        for i in range(len(sizes)-1): #Hasta uno menos del máximo porque cada capa está conectada con la siguiente
            self.layers.append(torch.nn.Linear(sizes[i],sizes[i+1])) #lleno la lista con las capas según los tamaños que quiero
            #Se agrega una capa totalmente conectada-> linear. sizes[1] es para entradas y [i+1] para salidas

    def forward(self,x): #Define como viajan los datos por la red
        h = x #Guardamos la entrada "x" en una variable que llamamos h
        for hidden in self.layers[:-1]: #Recorre todas las capas menos la última
            h = F.relu(hidden(h)) #esto es lo interesante, puedo aplicar cada elemento de torch.nn.ModuleList() como una función sobre tensores (aca son elementos de layers)
            #hidden -> aplica a la capa lineal
            #en este caso uso relu pero puede ser otra función de activación

        output = self.layers[-1] #Toma la última capa
        y = output(h) #Genera la salida al final de la red
        return y #Devuelve las predicciones-> el valor esperado


@torch.no_grad() #Evita que pytorch guarde la info para backpropagation porque solo la estamos evaluando. desactiva gradientes
def calcular_accuracy(predicciones, etiquetas): #Es un boolean que compara la predicción (valor esperado) vs valor real
    pred_clase = predicciones.argmax(dim=1) #busca el índice más alto en cada fila, o sea en la clase hecha anteriormente
    return (pred_clase == etiquetas).float().mean().item() 
#float: hace el boolean en 1 o 0, mean: calcula el promedio(porcentaje de aciertos), item: transfomra el tensor final en un número común para python

k_folds =  5
batch_number = 1

# Define a transform to normalize the data

transform = transforms.Compose([ #Junta varias transformaciones
    transforms.ToTensor(), #Convierte la imagen en un tensor
    transforms.Normalize((0.5,), (0.5,)) #Normaliza los valores del tensor
])

# Download and load the Fashion MNIST training data
train_dataset = torchvision.datasets.FashionMNIST( #Descarga el dataset de entrenamiento de uno de los imports
    root='./data',
    train=True, #Usa datos de entrenamiento
    download=True, #Desvarga el dataset si no existe
    transform=transform #Aplica transformaciones
)

# Download and load the Fashion MNIST test data
#Igual que el anterior pero False. 

test_dataset = torchvision.datasets.FashionMNIST(
    root='./data',
    train=False, #!!! ¿¿NO usa datos de entrenamiento??
    download=True,
    transform=transform
)

# Extract data and labels for KFold splitting
#Especificaciones de que hacer con las imagenes

X_train = train_dataset.data.view(-1, 28*28).float() / 255.0 # Normalize to [0, 1] if not using transforms.Normalize
y_train = train_dataset.targets

X_test = test_dataset.data.view(-1, 28*28).float() / 255.0 # Normalize to [0, 1] if not using transforms.Normalize
y_test = test_dataset.targets

# Create a TensorDataset for the training data
mnist_dataset = TensorDataset(X_train, y_train) #Une imagenes y etiquetas

images_per_fold = len(X_train)/k_folds #Cantidad de imagenes por fold
batch_size = int((len(X_train) - images_per_fold)/batch_number) #Tamaño del batch de entrenamiento
batch_size_val = int(images_per_fold/5) #Validación del batch--> ¿Después no se usa?

# KFold from sklearn
kf = KFold(n_splits=k_folds, shuffle=True) #Divide llos datos en 5 partes randoms. En 5 kfolds



# Initialize the network, loss function, and optimizer
criterion = nn.CrossEntropyLoss() #Función de pérdida para clasificación--> chequear softmax y entropía cruzada
l = []
epochs = 100 #Setteamos el num de epochs
repeticiones  = 1


#Hace 5 repeticiones por cada epoch-> 5 folds
acc = np.zeros ([repeticiones*5, epochs]) #Guarda las acurracies

# Training loop---> por cada kfold --> 5 kfolds por cada epoch
for k in range(repeticiones):
    for fold, (train_idx, val_idx) in enumerate(kf.split(mnist_dataset)): #Divide train y validación
        print(f"\nFold {fold+1}/{k_folds}")
        model = MLP([28*28 ,   10]) #Crea el modelo de redes neuronales--> En este caso no tiene capa oculta
        optimizer = optim.Adam(model.parameters(), lr=0.001) #Usa un optimizador "Adam"

        # Subset the dataset for the current fold
        train_subsampler = Subset(mnist_dataset, train_idx) #Le metemos los datos de entrenamiento
        val_subsampler = Subset(mnist_dataset, val_idx) #Le metemos los datos de validación

        #armo los dataloaders para aplicar batchs
        
        train_loader = DataLoader(train_subsampler, batch_size=batch_size, shuffle=True) #Carga batches de entrenamiento. Mezcla datos c/ shuffle
        val_loader = DataLoader(val_subsampler, batch_size=batch_size, shuffle=False) #Carga batches de validación. NO mezcla datos

        for epoch in range(epochs):

            # ===== TRAIN =====
            model.train()
            train_loss = 0.0

            for x_batch, y_batch in train_loader:
                optimizer.zero_grad() #reinicia gradientes
                logits = model(x_batch) #Forward propagation
                loss = criterion(logits, y_batch) #Calcula error
                loss.backward() #Backpropagation
                optimizer.step() #Actualiza los pesos sinápticos

                train_loss += loss.item() #Un contador que va acumulando pérdida------ ¿Por qué?

            train_loss /= len(train_loader)

            # ===== VALIDATION =====--> validamos la acurracy del modelo evaluado
            model.eval()
            val_acc = 0.0

            #Lo usa como cálculo del descenso por el gradiente
            with torch.no_grad():
                for x_val, y_val in val_loader:
                    preds = model(x_val) #Predicciones
                    val_acc += calcular_accuracy(preds, y_val) #Calcula acurracy

            val_acc /= len(val_loader)
            acc [fold+k*5, epoch] = val_acc #Guarda el acurracy
            print(f"Epoch {epoch} | loss {train_loss:.4f} | val acc {val_acc:.4f}")

#De acá sale el gráfico final
for i in range (repeticiones*5):
    plt.plot(acc[i , : ]) #Grafica acurray de cada fold



plt.xlabel("epoch") #Eje X
plt.ylabel("accuracy") #Eje Y